AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with a specified name.

Parameters:
  BucketNameParam:
    Type: String

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParam